# Generated by Django 2.2.10 on 2020-04-03 13:18

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0005_course_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='post_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
